name:        ${project.artifactId}
version:     ${project.version}
description: ${project.description}
author:      RoyCurtis
website:     https://github.com/Gamealition/SoftPlugin
main:        roycurtis.softplugin.SoftPlugin

permissions:
  softplugin.reload:
    description: Allow reloading of SoftPlugin, including recompile of Java source

commands:
  softplugin-reload:
    description: Reloads SoftPlugin config and recompiles all Java source
    aliases: [spr]
    permission: softplugin.reload
    usage: /<command>
